name: docker_remote

packages:
  - apps/**
  - packages/**

command:
  version:
    # Only allow versioning to happen on main branch.
    branch: main
    # Generates a link to a prefilled GitHub release creation page.
    releaseUrl: true

scripts:

  ci:
    run: melos run analyze && melos run format-check && melos run test

  get:
    run: melos exec -- flutter pub get
  
  clean:
    run: melos exec -- flutter clean

  lint:all:
    run: melos run analyze && melos run format
    description: Run all static analysis checks.

  analyze:
    run: |
      melos exec -c 10 -- \
        flutter analyze
    description: Run `flutter analyze` for all packages.

  format:
    run: melos exec dart format . --fix
    description: Run `dart format` for all packages.

  format-check:
    run: melos exec dart format . --set-exit-if-changed
    description: Run `dart format` checks for all packages.

  build:
    run: melos exec dart run build_runner build --delete-conflicting-outputs
    description: Run `build_runner` for all packages.
    packageFilters:
      dependsOn: build_runner

  test:
    run: melos run test:select --no-select
    description: Run all Flutter tests in all packages.
  
  test:select:
    run: melos exec -- flutter test
    packageFilters:
      dirExists: test
    description: Run all Flutter tests in this project.

  coverage:
    run: |
      melos exec -- flutter test --coverage &&
      melos exec -- genhtml coverage/lcov.info --output-directory=coverage/
    packageFilters:
      dirExists: test
    description: Generate coverage for the selected package.